[package]
name = 'hello_aptos'
version = '1.0.0'

[addresses]
hello_aptos = "_"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
